jupyterhub/systemdspawner

README.md

Just a coincidence that "1." at the end of a sentence fell on a new line. Simplest fix I could think of.

Fix "1." being interpreted as a start of a numbered list.

---

check-kernel.bash

Using grep on `/proc/config.gz` fails, whereas zgrep should work on all of the files in `possibleConfigs` whether they're compressed or not.

Use zgrep to search /proc/config.gz

---

README.md
systemdspawner/systemdspawner.py

Fixes #21. As noted in #21, systemd >= 231 requires the `CPUQuota` value to be an integer percentage. I ended up deciding it's best to be conservative and round down.

Convert CPUQuota value to an integer.

---

systemdspawner/systemdspawner.py

The logging call contained a stray %-entry.
I kept the order of the arguments and moved the user token to the front while removing the extra %s in the end of the string. Also adjusted the message slightly.

fix faulty log string

---

systemdspawner/systemdspawner.py

Allow Hub admins to add arbitrary properties for spawned Jupyter units.
Allow Hub admins to add arbitrary properties for spawned Jupyter units.
as an example, this configuration allows users to to scrape traffic and open up to 5000 files/sockets:
```
c.JupyterHub.spawner_class = 'systemdspawner.SystemdSpawner'
c.SystemdSpawner.use_sudo = True
c.SystemdSpawner.unit_extra_properties = ['AmbientCapabilties=CAP_NET_RAW', 'LimitNOFILE=5000']
```

support adding properties for singleuser units

---

README.md
dev-requirements.txt
systemdspawner/systemd.py
systemdspawner/systemdspawner.py
tests/test_systemd.py

- Use async/await syntax, require Python 3.5
- Separate systemd related calls into own file
- Add unit tests for systemd related calls
- Use asyncio process rather than blocking subprocess calls.
This also makes us use Tornado 5.0+
- Switch unit_extra_properties to be a Dict rather than List.
This is more flexible. It's a breaking change, but the release
with unit_extra_properties is so new this is ok.
- ReadOnlyPaths no longer prepends a '-' in front of the paths.
This was an oversight earlier. This means units will fail
if there's a path there that does not exist.
- use_sudo is no longer supported. It offered questionable security.
JupyterHub services should be secured with other mechanisms instead.
If we really want to support sudo, we can do so at a later time.

Refactor & add unit tests

---

systemdspawner/systemdspawner.py

There is no systemd.stop, only stop_service
Additionally, log what's about to happen, rather than after it happened, in case there is an error.

Fix call to systemd.stop_service

---

systemdspawner/systemd.py
systemdspawner/systemdspawner.py
tests/test_systemd.py

If a user's service enters a failed state, the spawner can never recover until the state is reset manually on the host. This change will have the spawner check the state before it tries to spin up a new instance and if the state is failed, will attempt to reset it.
FIXES #44

Check state of service before startup and reset if failed

---

tests/test_systemd.py

The original test tries to create a failed service by passing it a uid that doesn't exist, which works as intended on systemd=229, but results in a service created in an `inactive` rather than `failed` state on systemd=239.
This commit changes the test and has it try to create a service with an invalid working dir instead of uid, and has been confirmed to work on both versions as the created service fails with an error of `200/CHDIR`.

Fix unit-test for service_failed to work on systemd>229

---

README.md
systemdspawner/systemd.py
systemdspawner/systemdspawner.py
tests/test_systemd.py

Let jupyterhub to configured to spawn users into a given predefined slice.  
This allows an administrator of a jupyerhub instance to limit memory/cpu usage as well as constrain access to devices etc for all users collectively under a given spawner.
Quite useful for example to limit all of jupyterhub to 1GB less than the total system memory for example

Add simple slice support to systemd spawner

---

README.md
setup.py

As of JupyterHub 1.0, spawners can register themselves via [entry point meta data](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html#registering-custom-spawners-via-entry-points). We've found this to be extremely useful, particularly as the generated configs would list the systemdspawner as one of the available spawners if it is installed.

Add spawner entry points

---

README.md

This one might come in handy for installations in environments that are highly customised or have specific requirements.
Mention it explicitly in the documentation so users do not have to go through the code or issues.
If this option isn't documented by design cause it is considered *kludgy*, feel free to disregard and drop the PR.

Add documentation for unit_extra_properties option

---

tests/test_systemd.py

test failed because it assumed ExecStartPre ran in working_dir, which it does not

get test_properties_list passing

---

README.md
systemdspawner/systemdspawner.py

It would be useful to be able to expand user values in the configuration
options that are passed to the transient systemd unit file. This commit
enables that option and updates the documentation accordingly.
Fixes: #82

Expand user variables within unit_extra_parameters

---

systemdspawner/systemd.py

This fixes a bug in systemd which terminate all processes in the scope if a process hits the mem_limit.
It seems to be fixed upstream, but might take a while until the distros implements it. https://github.com/systemd/systemd/issues/25376

Don't kill the whole service when a single proces OOMs

---

pyproject.toml
setup.py

I want to drop support just to make future maintenance easier, and do it before 1.0.0 is released - something I work towards now to ship with the littlest jupyterhub distribution that is also about to release 1.0.0.
For example I know pytest-jupyterhub that I may want to use in order to help test this spawner requires py38 and jupyterhub 2.3.

maint, breaking: require python 3.8+, jupyterhub 2.3.0+, tornado 5.1+

---

systemdspawner/systemdspawner.py

Protects against vulnerabilities such as
https://arstechnica.com/information-technology/2022/01/a-bug-lurking-for-12-years-gives-attackers-root-on-every-major-linux-distro/
or the previous sudo vulnerability.
Equivalent of https://github.com/jupyterhub/kubespawner/pull/545
This should be counted as a braking change.

Disable user sudo by default

---

README.md

We have badges (#112) to help nudge users to report issues and ask for help.
The mailing list may be relevant still, I've never used it so I don't
know if its suitable to suggest people to write there.

readme: remove resources section and link to discourse forum instead of mailing list

---

.github/workflows/test.yaml
README.md
systemdspawner/systemd.py
systemdspawner/systemdspawner.py
tests/test_systemd.py

This makes existing requirements explicit, but doesn't increase them. Due to that, its not really breaking.
- **Explicitily fail on startup when systemd version <243**
This isn't breaking because v0.17 is already broken for systemd version <243 because the OOMPolicy config set in #101 was [introduced in systemd version 243] (https://github.com/systemd/systemd/commit/afcfaa695cd00b713e7d57e1829da90b692ac6f8) and makes user servers fail to start.
- **Warn on startup when systemd versions <245**
This is motivated by us only testing on systemd version 245.
- **Add tests against systemd version 245 in Ubuntu 20.04** 
Version 245 is easy for us to test against, because its part of Ubuntu 20.04. Yuvi suggested testing against the second most newest ubuntu LTS release's systemd version, which is …

Require systemd v243+, recommend systemd v245+, test against systemd v245

---

.github/workflows/test.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
setup.py
tests/conftest.py
tests/test_systemd.py
tests/test_systemdspawner.py

Test coverage before this PR:
```
---------- coverage: platform linux, python 3.11.3-final-0 -----------
Name                               Stmts   Miss  Cover
------------------------------------------------------
systemdspawner/__init__.py             2      0   100%
systemdspawner/systemd.py             70      5    93%
systemdspawner/systemdspawner.py     100     72    28%
------------------------------------------------------
TOTAL                                172     77    55%
```
Test coverage after this PR:
```
---------- coverage: platform linux, python 3.11.3-final-0 -----------
Name                               Stmts   Miss  Cover
------------------------------------------------------
systemdspawner/__init__.py             2      0   100%
systemdspawner/systemd.py …
```

Add basic start/stop test against a jupyterhub

---

systemdspawner/systemd.py

- We had avoided using systemd-run's `--working-directory` flag because it was added in systemd v229 or similar, but now we can assume we have that.
- I saw an opportunity to help me, my future self, and hopefully others to understand the code better by refactoring it a bit and adding some comments with references to systemd stuff, so I took it.

Rely on systemd-run's --working-directory, and refactor for readability

---

systemdspawner/systemdspawner.py

Closes #126 where I did an investigation related to the removed fixme notes.
This change should not be breaking because MemoryMax replaces MemoryLimit according to docs, and has been documented to do that since v243 at least. See #126 for investigative notes about that.

Replace deprecated MemoryLimit with MemoryMax, remove fixme notes

---

systemdspawner/systemd.py
tests/test_systemd.py

systemd requires absolute paths for executables in order to resolve as expected.
Relative path executables do not take $PATH env into account when resolving the executable, only after launching the process, so `systemd-run bash -c exe` works, while just `systemd-run exe`  will not.
The default executable for a Spawner is the relative `jupyterhub-singleuser`, assuming  $PATH will be resolved.
Fixes the failure in https://github.com/jupyterhub/the-littlest-jupyterhub/pull/915

ensure executable paths are absolute

---

systemdspawner/systemdspawner.py

I'm not sure if this is sufficient to resolve issues with using `extra_paths` together with jupyterhub 5.2.0 where `env_keep` doesn't include `PATH` in the Spawner base class any more, but it should probably be an incremental improvement no matter what.
See [debugging notes](https://github.com/jupyterhub/the-littlest-jupyterhub/pull/1008) in the littlest jupyterhub distribution when trying to upgrade jupyterhub from 5.1.0 to 5.2.0.
I've not added a test for `extra_paths` in this project, but it gets tested via tljh though, and via https://github.com/jupyterhub/the-littlest-jupyterhub/pull/1008 I can see that this made a positive difference making tests pass where they previously failed.

Stop assuming PATH env is defined when extra_paths is set, and then initialize to os.defpath
